version: '3'

services:

  stats-app:
    image: grafana/grafana
    user: "$UID:$GID"
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - "$PWD:/var/lib/grafana"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel

  db-app:
    image: influxdb
    network_mode: host
    ports:
      - 8086:8086
    volumes:
      - "$PWD:/var/lib/influxdb"


